---
name: build and test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 16 * * 5" # Every Friday 16:00 UTC


jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    container:
      image: perldocker/perl-tester:5.32
    steps:
      - uses: actions/checkout@v2
      - name: Build distribution
        run: auto-build-and-test-dist
      - uses: actions/upload-artifact@master
        with:
          name: build_dir
          path: build_dir
  test_linux:
    runs-on: ${{ matrix.os }}
    name: "Perl ${{ matrix.perl-version }} on ${{ matrix.os }}"
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        perl-version:
          - "5.10"
          - "5.18"
          - "5.24"
          - "5.28"
          - "5.30"
          - "5.32"
          - "5.34"
          - "5.36"
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build_dir
          path: .
      - name: Install dependencies
        if: success()
        run: cpanm --quiet --installdeps --notest .
      - name: Run Tests
        if: success()
        run: prove --lib --jobs $(nproc --all) t
